services:
  mysql:
    container_name: mysql-spring-jpa
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: springdemodb
      MYSQL_USER: springdemo
      MYSQL_PASSWORD: springdemo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

    volumes:
      - ./data:/var/lib/mysql
