services:
  mysql:
    container_name: mysql-spring-jpa
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    pull_policy: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
